//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaccation
    {
        public int Id { get; set; }
        public int VaccationDuration { get; set; }
        public Nullable<System.DateTime> VaccationStartDay { get; set; }
        public Nullable<System.DateTime> VaccationEndDate { get; set; }
        public int EmployeeID { get; set; }
        public string EmployeeTier { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
